// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "";
const SUPABASE_PUBLISHABLE_KEY = "";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const LOCAL_SUPABASE_URL = typeof localStorage !== 'undefined' ? localStorage.getItem('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFibnpkbmpraW9lYmVnenZvb2xkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDg0OTE0MCwiZXhwIjoyMDcwNDI1MTQwfQ.qsbCItMBHRLuIT9sFzIVlJINy7ttxNyvMBdGSwiFA1A') : null;
const LOCAL_SUPABASE_ANON = typeof localStorage !== 'undefined' ? localStorage.getItem('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFibnpkbmpraW9lYmVnenZvb2xkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDkxNDAsImV4cCI6MjA3MDQyNTE0MH0.pVax3Wgi-q1tWY3TzsRFUScpgDWhAnMsgCKQGMBivXk') : null;

const RESOLVED_URL = LOCAL_SUPABASE_URL || SUPABASE_URL;
const RESOLVED_ANON = LOCAL_SUPABASE_ANON || SUPABASE_PUBLISHABLE_KEY;

export const supabase = createClient<Database>(RESOLVED_URL, RESOLVED_ANON, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});